#include<iostream.h>
#include<conio.h>
void main()
{
 clrscr();
 cout<<"\t\t\tSAGAR 11-A COMPUTER SCIENCE STUDENTS\n";
 cout<<"\n 1.ADHITHYA";
 cout<<"\n 2.AKSHAY RAM SHANJAYAN";
 cout<<"\n 3.DHARANEESH";
 cout<<"\n 4.FAZIL AHEMED";
 cout<<"\n 5.HARIN";
 cout<<"\n 6.NANDHA PRABHU";
 cout<<"\n 7.SAKTHIVEL";
 cout<<"\n 8.SUSHIL KUMAR";
 cout<<"\n 9.SUGHEESHAN";
 cout<<"\n 10.TRISHUL GANDHI";
 getch();
 }

