#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
cout<<"\n\t\t\tSAGAR INTERNATIONAL SCHOOL";
cout<<"\n\t\t\t\t11-A IIT C.S";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\tS.NO\t\tSTUDENTS NAME";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\t1.\t\tADHITHYA";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\t2.\t\tAKSHAY";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\t3.\t\tDHARANIESH";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\t4.\t\tFAZIL AHEMED";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\t5.\t\tHARIN";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\t6.\t\tNANDHA PRABHU";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\t7.\t\tSAKTHIVEL";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\t8.\t\tSUSHIL KUMAR";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\t9.\t\tSUGHEESHAN";
cout<<"\n\t\t___________________________________________";
cout<<"\n\t\t10.\t\tTRISHUL GANDHI";
cout<<"\n\t\t___________________________________________";
getch();
}