#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
cout<<"\n\t\t\tSAGAR INTERNATIONAL SCHOOL";
cout<<"\n\t\t\tSUGHEESHAN 11-A IIT C.S";
cout<<"\n\t\t____________________________________________";
cout<<"\n\t\tS.NO\t\tSUBJECTS\t\MARKS SCORED";
cout<<"\n\t\t____________________________________________";
cout<<"\n\t\t1.\t\tENGLISHt\t\t98";
cout<<"\n\t\t____________________________________________";
cout<<"\n\t\t2.\t\tTAMIL\t\t\t97";
cout<<"\n\t\t____________________________________________";
cout<<"\n\t\t3.\t\tMATHS\t\t\t92";
cout<<"\n\t\t____________________________________________";
cout<<"\n\t\t4.\t\tSCIENCE\t\t\t95";
cout<<"\n\t\t____________________________________________";
cout<<"\n\t\t5.\t\tCOMPUTER SCIENCE\t97";
cout<<"\n\t\t____________________________________________";
cout<<"\n\t\t6.\t\tTOTAL\t\t\t"<<98+97+92+95+97;
cout<<"\n\t\t____________________________________________";
cout<<"\n\t\t7.\t\tpercentage\t\t"<<479/5.0;
cout<<"\n\t\t____________________________________________";
getch();
}